version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
